trigger:
  - main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:
- stage: Tests
  displayName: Tests stage
  jobs:
  - job: Tests
    displayName: Tests
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        npm i cypress
        npx cypress
      displayName: Instalar o Cypress via npm
    - script: |
        npx cypress run --reporter junit --reporter-options "mochaFile=results/output-tests-cypress.xml"
      displayName: Executar o Cypress via npx
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/output-tests-cypress.xml'
      displayName: Publicar resultado dos testes (XML JUnit)
      condition: always()
- stage: Build
  displayName: Build stage
  dependsOn: Tests
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: echo 'Operacao simulando build da aplicacao...'
      displayName: 'Simulacao (Build)'